#!/bin/bash
BASEDIR=`pwd`
echo "Please input name of project"
read PROJECT
PROJECTPATH=${BASEDIR}"/${PROJECT}"
mkdir -p ${PROJECTPATH}/{include,source,shared,resource/{media/{images,audio,video},configs,document},debug,release,bin,note/{media,css,js,doc,WebContent}}
cd ${PROJECTPATH}
# （1）Include目录存放应用程序的头文件（.h），还可以再细分子目录。
# 
# （2）Source目录存放应用程序的源文件（.c或 .cpp），还可以再细分子目录。
# 
# （3）Shared目录存放一些共享的文件。
# 
# （4）Resource目录存放应用程序所用的各种资源文件，包括图片、视频、音频、图标、光标、对话框等，还可以再细分子目录。
# 
# （5）Debug目录存放应用程序调试版本生成的中间文件。
# 
# （6）Release目录存放应用程序发行版本生成的中间文件。
# 
# （7）Bin目录存放程序员自己创建的lib文件和dll文件。
